#!/bin/bash
# Exit on first error, show commands as they run.
set -ex

INITIALIZE=0
if [ ! -d /var/lib/mysql/mysql ];
then
  INITIALIZE=1
  mysql_install_db --datadir=/var/lib/mysql
fi

/usr/sbin/mysqld $@ &

if [ $INITIALIZE -eq 1 ];
then
  sleep 5;
  mysql -uroot -e 'GRANT ALL PRIVILEGES ON *.* TO "root"@"%" WITH GRANT OPTION'
fi

exec tail -f /var/log/mysql.log
